name: Build, Test, and Docs

on: [push, pull_request,workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:
  # --------------------------------
  # 1Ô∏è‚É£ Build & test the environment
  # --------------------------------
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Micromamba (with caching)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
          micromamba-version: "latest"
      - name: Set git identity for testing
        run: |
          git config --global user.email "runner@example.com"
          git config --global user.name "CI Runner"
      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest -v --maxfail=1 --disable-warnings --cov --cov-branch --cov-report=xml
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}



  # --------------------------------
  # 2Ô∏è‚É£ Build Sphinx documentation
  # --------------------------------
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Micromamba (with caching)
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml    
          cache-environment: true
          cache-downloads: true
          micromamba-version: "latest"

      - name: Build Sphinx docs
        shell: bash -l {0}
        run: |
          sphinx-build -b html .docstr docs

      - name: Deploy PR preview to GitHub Pages
        if: github.event_name == 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs
          destination_dir: pr-${{ github.event.number }}
          keep_files: false 

      - name: Comment PR with preview link
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            üìÑ Preview your docs here:
            üëâ https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-${{ github.event.number }}/index.html

      - name: Deploy main to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
